version: "3"

services:
  node:
    image: node
    ports:
      - 8000:8000
    volumes:
      - .:/src
    working_dir: /src
    depends_on:
      - mongodb
    command: tail -f /dev/null
    tty: true
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
