name: Simple workflow
on: push
jobs:
  build:
    name: NodeJS action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose up -d
    - run: docker-compose exec -T node npm install
    - run: docker-compose exec -T node npm test